all: embaralhando uma-volta rodando

embaralhando: embaralhando.cpp
	g++ -Wall -ansi -O2 -pedantic -lSDL -lSDL_image -lSDL_gfx embaralhando.cpp -o embaralhando

uma-volta: uma-volta.cpp
	g++ -Wall -ansi -O2 -pedantic -lSDL -lSDL_image -lSDL_gfx uma-volta.cpp -o uma-volta

rodando: rodando.cpp
	g++ -Wall -ansi -O2 -pedantic -lSDL -lSDL_gfx -lSDL_image rodando.cpp -o rodando